[package]
name = "{{ project-name }}"
version = "0.1.0"
authors = ["Tyr Chen <tyr.chen@gmail.com>"]
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/"
repository = "https://github.com/tyrchen/"
homepage = "https://github.com/tyrchen/"
description = """

"""
readme = "README.md"
categories = ["development-tools"]
keywords = []

[dependencies]
